### ISSUE TITLE
Setting up desktop builds

### ISSUE THREAD

**Issue by cedkim** [makeaixstudio/desktop#1]
The desktop version of AIX Studio 2 was not building properly, leaving out many core modules. When these modules were included, electron-forge stopped working. The switch to electron-builder is in progress.

**Comment by cedkim** [comment]
It appears that a dependency won't download. Not sure what this is.

```
error /Users/runner/work/desktop/desktop/node_modules/vscode-ripgrep: Command failed.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments: 
Directory: /Users/runner/work/desktop/desktop/node_modules/vscode-ripgrep
Output:
Finding release for v12.1.1
GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v12.1.1
Deleting invalid download cache
Downloading ripgrep failed: Error: Request failed: 403
    at ClientRequest.https.get.response (/Users/runner/work/desktop/desktop/node_modules/vscode-ripgrep/lib/download.js:127:24)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
    at TLSSocket.socketOnData (_http_client.js:451:20)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
```

**Comment by cedkim** [comment]
This seems to only be an issue with Mac and Linux builds. I'll look into it.

**Comment by cedkim** [comment]
This also seems to be an upstream issue, since even an official Electron-powered Theia IDE has this issue. See [this issue on their page](https://github.com/theia-ide/yangster-electron/issues/30).

**Comment by cedkim** [comment]
Commit fe7f9ee6dcae51d002f7ca74da253ddf89856357 may or may not fix this issue. Let's just see what it does.

**Comment by cedkim** [comment]
This didn't solve the Linux issue, but commits cf9a4f475b58ca83e51dff128424a15340dd1ee2 and 9b016b6202dd318d3b46b8eb1f73b634cfe789c8 should.

**Comment by cedkim** [comment]
There were a few issues, but I think 1a6c762803b157b765ebb11976ef23fde7219cb4 is going to solve the Linux issue.
I think.

**Comment by cedkim** [comment]
It built successfully! Time for testing.
